USE [PII IV]
GO

/****** Object:  Table [dbo].[OutroJogoRedeSocial]    Script Date: 31/10/2023 21:57:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OutroJogoRedeSocial](
	[idOutroJogoRedeSocial] [int] IDENTITY(1,1) NOT NULL,
	[nome] [text] NOT NULL,
	[tipo] [varchar](50) NOT NULL,
 CONSTRAINT [PK_OutroJogoRedeSocial] PRIMARY KEY CLUSTERED 
(
	[idOutroJogoRedeSocial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

